Secure image upload
fileverse/fileverse-ddoc pull request #107
Opened 2024-10-08 14:30 UTC by EldarLazhuyeu

Integrated secure image upload to current upload image feature:
<img width="1305" alt="Screenshot 2024-10-08 at 16 28 52" src="https://github.com/user-attachments/assets/c8ec2943-78d0-47c8-aeee-0266975891b0">

1. Image is red from the UI.
2. Sending image with public RSA key to the api.
3. Receive back image url, encrypted key and image vector.
4. Render image in the editor

2024-10-09 08:01 UTC, nadeem-fileverse requested changes
PTAL

2024-10-09 08:01 UTC, nadeem-fileverse commented on package/utils/upload-images.tsx
> +      ivBuffer: new Uint8Array(iv.data),
After the upload is done, decrypting the image and display should be handled by resizableMedia

2024-10-09 08:01 UTC, nadeem-fileverse commented on package/utils/upload-images.tsx
> +      src: `data:image/jpeg;base64,${imageBase64}`,
resizable media for this case should take the URL as the src along with other props required to decrypt the image.
Also in order to make this backwards compatible we should add another `media-type` something like `secure-img`

2024-10-09 08:01 UTC, nadeem-fileverse commented on package/utils/upload-images.tsx
> +    const response = await fetch(`${import.meta.env.VITE_FILEVERSE_IMAGES_API_URL}/upload`,{
URL should be supplied as a prop

2024-10-09 08:01 UTC, nadeem-fileverse commented on package/utils/upload-images.tsx
> +    const response = await fetch(`${import.meta.env.VITE_FILEVERSE_IMAGES_API_URL}/upload`,{
In case the upload url is not provided it should fallback to previous implementation with size limitation

2024-10-09 08:09 UTC, nadeem-fileverse commented on package/utils/upload-images.tsx
> +      src: `data:image/jpeg;base64,${imageBase64}`,
Point to remember is that we want to save the image url and decryption information in the JSON content of the ddoc. If we save the base64 data url for the image the size of the json content increases

2024-10-10 04:21 UTC, kylengn approved these changes
LGTM

2024-10-10 06:29 UTC, merged