DDO-11
fileverse/fileverse-ddoc pull request #121
Opened 2024-10-17 11:30 UTC by SrishtiLodhi

2024-10-17 12:42 UTC, kylengn requested changes

2024-10-17 12:42 UTC, kylengn commented on package/extensions/page-break.ts
> +                console.log(
remove

2024-10-17 12:42 UTC, kylengn commented on package/extensions/page-break.ts
> +              console.log('Remove page break image clicked');
remove

2024-10-17 12:42 UTC, kylengn commented on package/extensions/page-break.ts
> +            } else {
remove else if not having any operation

2024-10-17 21:28 UTC, SrishtiLodhi commented on package/extensions/page-break.ts
> +                console.log(
I have removed this

2024-10-17 21:31 UTC, SrishtiLodhi commented on package/extensions/page-break.ts
> +            } else {
removed it 👀

2024-10-18 06:00 UTC, SrishtiLodhi commented on package/extensions/page-break.ts
> +              console.log('Remove page break image clicked');
Removed the console

2024-10-18 08:37 UTC, kylengn approved these changes

2024-10-18 09:10 UTC, merged